spring:
   profiles:
      active: dev
   jackson:
      date-format: "yyyy-MM-dd HH:mm:ss"
      time-zone: "GMT+8" 
server: 
   port: 8089
   servlet: 
      context-path: /gogirl_user
   tomcat:
      max-threads: 10
logging: 
   config: classpath:logback-boot.xml
   level:
      com.gogirl.gogirl_user.dao : debug
mybatis:
   mapper-locations: classpath:mapper/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql