spring:
   datasource:
      url: jdbc:mysql://cdb-554jnvol.gz.tencentcdb.com:10105/bailun_manicure?useUnicode=true&characterEncoding=utf-8
      username: root
      password: "#7kfnymAM$Y9-Ntf"
      driver-class-name: com.mysql.jdbc.Driver
   jackson:
      date-format: "yyyy-MM-dd HH:mm:ss"
      time-zone: "GMT+8"
gogirl:
  GOGIRLORDER: "http://127.0.0.1:8084/"
  GOGIRLMP: "http://127.0.0.1:8088/"